{% set name = "lunarcalendar-ext" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/LunarCalendar-ext-{{ version }}.tar.gz
  sha256: e9afee2869e131b8a0c1d23dc067232b78c52f97dcf3d00b239eea867d398d2c
  patches:
    - 0001-add-version-var.patch

build:
  number: 1
  noarch: python
  entry_points:
    - lunar-find=lunarcalendar.command:find
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ephem >=3.7.5.3
    - python >={{ python_min }}
    - python-dateutil >=2.6.1
    - pytz

test:
  source_files:
    - tests
  imports:
    - lunarcalendar
  commands:
    - pip check
    - set PYTHONUTF8=1
    - lunar-find --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/KaixuYang/LunarCalendar-extension
  summary: A bugfix fork of LunarCalendar, a Lunar-Solar calendar converter.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
